const SKILL_DATA = [
  {
    name: 'フニャリズム',
    heartCost: 20,
    type: 'デバフスキル',
    description: '相手全員の守備力を大きく下げる。',
  },
  {
    name: 'カチムキン',
    heartCost: 20,
    type: 'バフスキル',
    description: '自分の攻撃力と守備力を少し上げる。',
  },
  {
    name: 'カナシバルト',
    heartCost: 20,
    type: '状態異常',
    description: 'ダメージを与えつつしびれ状態にする。しびれ状態のモンスターは1~3ターンの間、行動不能になる。',
  },
  {
    name: 'モード・バリア',
    heartCost: 20,
    type: 'バフスキル',
    description: 'HPが3/4以上ある時、最大HPの半分のダメージを受け、自分の守備力を大きく上げる。',
  },
  {
    name: 'おやつのじかん',
    heartCost: 20,
    type: '回復・カウンター',
    description: '自分のHPを45回復し、攻撃力を少し上げる。',
  },
  {
    name: 'だいちのいかり',
    heartCost: 20,
    type: '物理攻撃',
    description: 'モンスター1体に大ダメージ。',
  },
  {
    name: 'ユルミノウタ',
    heartCost: 20,
    type: 'デバフスキル',
    description: '相手全員の攻撃力約3/4倍',
  },
  {
    name: 'つきくずし',
    heartCost: 20,
    type: '物理攻撃',
    description: 'モンスター1体にダメージを与えつつ、攻撃力を少し下げる。',
  },
  {
    name: 'ガオガオスラッシュ',
    heartCost: 20,
    type: '物理攻撃',
    description: 'モンスター1体にダメージを与えた後、自分の攻撃力を上げる。何度も使うと武器を失って攻撃がねこパンチになる。',
  },
  {
    name: 'ナイトメーア',
    heartCost: 20,
    type: '物理攻撃',
    description: '敵全体に通常攻撃分のダメージ、素早さを下げる',
  },
  {
    name: 'ニャンニャンドレイン',
    heartCost: 20,
    type: '物理攻撃',
    description: 'モンスター1体にダメージを与え、自分のHPを少し回復する。',
  },
  {
    name: 'ぷるぷるカウンター',
    heartCost: 20,
    type: '回復・カウンター',
    description: '相手の攻撃を跳ね返す「ぷるぷるカウンター状態」になる。魔法攻撃やスキルは跳ね返せない。',
  },
  {
    name: 'ハナカグラ',
    heartCost: 20,
    type: '魔法攻撃',
    description: '相手1体に花びらの弾で攻撃。魔法に弱いモンスターに大ダメージ。',
  },
  {
    name: 'ダウナースロット',
    heartCost: 20,
    type: 'デバフスキル',
    description: '相手1体のいずれかの能力を下げるか、いずれかの状態異常にする。',
  },
  {
    name: 'ファイーア',
    heartCost: 10,
    type: '魔法攻撃',
    description: '相手1体に炎の魔法攻撃。「ギガファイーア」に進化可能。',
  },
  {
    name: 'ギガファイーア',
    heartCost: 30,
    type: '魔法攻撃',
    description: '「ファイーア」から進化。相手1体に炎の魔法攻撃。',
  },
  {
    name: 'アイース',
    heartCost: 10,
    type: '魔法攻撃',
    description: '相手1体に氷の魔法攻撃。HPが低い時に発動確率が上がる。「ギガアイース」に進化可能。',
  },
  {
    name: 'ギガアイース',
    heartCost: 30,
    type: '魔法攻撃',
    description: '「アイース」から進化。HPが低い時に発動確率が上がる。相手1体に氷の魔法攻撃。',
  },
  {
    name: 'サンーダ',
    heartCost: 10,
    type: '魔法攻撃',
    description: '相手1体に雷の魔法攻撃。HPが高い時に発動確率が上がる。「ギガサンーダ」に進化可能。',
  },
  {
    name: 'ギガサンーダ',
    heartCost: 30,
    type: '魔法攻撃',
    description: '「サンーダ」から進化。相手1体に雷の魔法攻撃。HPが高い時に発動確率が上がる。',
  },
  {
    name: 'するどいキバ',
    heartCost: 15,
    type: '物理攻撃',
    description: '相手1体に攻撃力を1.5倍にして攻撃。',
  },
  {
    name: 'ドリルスピン',
    heartCost: 15,
    type: '物理攻撃',
    description: '通常攻撃の約1.5倍',
  },
  {
    name: 'おしつぶし',
    heartCost: 15,
    type: '物理攻撃',
    description: '相手1体に元々の攻撃力を約2倍にして攻撃。HPが低い時発動確率が上がる。',
  },
  {
    name: 'シビルト',
    heartCost: 20,
    type: '状態異常',
    description: '相手1体をしびれ状態にする。しびれ状態のモンスターは1~3ターンの間行動不能になる。',
  },
  {
    name: 'リフレシュ',
    heartCost: 10,
    type: '回復・カウンター',
    description: '自分のHPを150回復か。「チョーリフレシュ」に進化可能。',
  },
  {
    name: 'チョーリフレシュ',
    heartCost: 30,
    type: '回復・カウンター',
    description: '「リフレシュ」から進化。自分のHPを209~?回復。',
  },
  {
    name: 'ピヨルト',
    heartCost: 20,
    type: '状態異常',
    description: '相手1体を数ターンこんらん状態にする。こんらん状態のモンスターは一定の確率で自分自身を攻撃する。',
  },
  {
    name: 'ドクルト',
    heartCost: 20,
    type: '状態異常',
    description: 'モンスターを毒状態にし、毎ターン行動後最大HPの約1/6ダメージ。ボス討伐においてかなり優秀。2~3回目で発動すれば必ず制限ターン内に決着がつきます。',
  },
  {
    name: 'ムキムキン',
    heartCost: 10,
    type: 'バフスキル',
    description: '自分の攻撃力を上げる。「バキバキン」に進化可能。',
  },
  {
    name: 'バキバキン',
    heartCost: 30,
    type: 'バフスキル',
    description: '「ムキムキン」から進化。自分の攻撃力を約2倍上げる。',
  },
  {
    name: 'カチコチン',
    heartCost: 10,
    type: 'バフスキル',
    description: '自分の守備力を上げる。「ガチガチン」に進化可能。',
  },
  {
    name: 'ガチガチン',
    heartCost: 30,
    type: 'バフスキル',
    description: '「カチコチン」から進化。自分の守備力を大きく上げる。',
  },
  {
    name: 'キビキビン',
    heartCost: 10,
    type: 'バフスキル',
    description: '自分の素早さを上げる。「シュビシュビン」に進化可能。',
  },
  {
    name: 'シュビシュビン',
    heartCost: 30,
    type: 'バフスキル',
    description: '「キビキビン」から進化。自分の素早さを大きく上げる。',
  },
  {
    name: 'ピタピタン',
    heartCost: 10,
    type: 'バフスキル',
    description: '自分の命中率を上げる。「バチバチン」に進化可能。',
  },
  {
    name: 'バチバチン',
    heartCost: 30,
    type: 'バフスキル',
    description: '「ピタピタン」から進化。自分の命中率を大きく上げる。',
  },
  {
    name: 'ズバズバン',
    heartCost: 10,
    type: 'バフスキル',
    description: 'クリティカル率を上げる。「ズドズドン」に進化可能。',
  },
  {
    name: 'ズドズドン',
    heartCost: 30,
    type: 'バフスキル',
    description: '「ズバズバン」から進化。クリティカル率を大きく上げる。',
  },
  {
    name: 'フニャムキン',
    heartCost: 10,
    type: 'バフスキル',
    description: '自分の守備力が大きく下がる代わりに攻撃力を大きく上げる。',
  },
  {
    name: 'ポヨポヨン',
    heartCost: 10,
    type: 'バフスキル',
    description: '自分の魔法守備力を上げる。「ブヨブヨン」に進化可能。',
  },
  {
    name: 'ブヨブヨン',
    heartCost: 30,
    type: 'バフスキル',
    description: '「ポヨポヨン」から進化。自分の魔法守備力を大きく上げる。',
  },
  {
    name: 'カシコイン',
    heartCost: 10,
    type: 'バフスキル',
    description: '自分の魔法攻撃力を上げる。「インテリン」に進化可能。',
  },
  {
    name: 'インテリン',
    heartCost: 30,
    type: 'バフスキル',
    description: '「カシコイン」から進化。自分の魔法攻撃力を大きく上げる。',
  },
  {
    name: 'フニャルト',
    heartCost: 10,
    type: 'デバフスキル',
    description: '相手1体の守備力を下げる。「フニャフニャルト」に進化可能。',
  },
  {
    name: 'フニャフニャルト',
    heartCost: 30,
    type: 'デバフスキル',
    description: '「フニャルト」から進化。相手1体の守備力を1/4もしくは-60から-70する(検証中)。',
  },
  {
    name: 'シオルト',
    heartCost: 10,
    type: 'デバフスキル',
    description: '相手1体の攻撃力を下げる。「シオシオルト」に進化可能。',
  },
  {
    name: 'シオシオルト',
    heartCost: 30,
    type: 'デバフスキル',
    description: '「シオルト」から進化。相手1体の攻撃力を半分にする。討伐戦においてかなり優秀。',
  },
  {
    name: 'オソルト',
    heartCost: 10,
    type: 'デバフスキル',
    description: '相手1体の素早さを下げる。「オソオソルト」に進化可能。',
  },
  {
    name: 'オソオソルト',
    heartCost: 30,
    type: 'デバフスキル',
    description: '「オソルト」から進化。相手1体の素早さを大きく下げる。',
  },
  {
    name: 'ブレルト',
    heartCost: 10,
    type: 'デバフスキル',
    description: '相手1体の命中率を下げる。「ブレブレルト」に進化可能。',
  },
  {
    name: 'ブレブレルト',
    heartCost: 30,
    type: 'デバフスキル',
    description: '「ブレルト」から進化。相手1体の命中率を大きく下げる。討伐戦においてかなり優秀。',
  },
  {
    name: 'ポヤルト',
    heartCost: 10,
    type: 'デバフスキル',
    description: '相手1体の魔法攻撃力を下げる。「ポヤポヤルト」に進化可能。',
  },
  {
    name: 'ポヤポヤルト',
    heartCost: 30,
    type: 'デバフスキル',
    description: '「ポヤルト」から進化。相手1体の魔法攻撃力を大きく下げる。',
  },
  {
    name: 'カサルト',
    heartCost: 10,
    type: 'デバフスキル',
    description: '相手1体の魔法守備力を下げる。「カサカサルト」に進化可能。',
  },
  {
    name: 'カサカサルト',
    heartCost: 30,
    type: 'デバフスキル',
    description: '「カサルト」から進化。相手1体の魔法守備力を大きく下げる。',
  },
];
